"""Phase 4 — build the DPO preference dataset (human + synthetic pairs).

Outputs:
  * ``data/synthetic/preference_pairs.jsonl``  — expanded (oversampled) records
  * ``data/synthetic/pairs_stats.json``
  * ``outputs/preference_dataset.png``

Synthetic pairs come from (a) the seed corpus (always) and (b) optional
on-policy candidates generated by the SFT model (``--n-onpolicy``). Both are
scored by the static judge and paired by score margin.

Usage:
    python scripts/04_build_pairs.py
    python scripts/04_build_pairs.py --dummy            # tiny, no model needed
    python scripts/04_build_pairs.py --n-onpolicy 200 --sft-model models/sft
"""

from __future__ import annotations

import argparse
import json
import random

import _bootstrap  # noqa: F401

from mariodpo_v2.constants import (
    DATA_PROCESSED_DIR,
    DATA_RAW_DIR,
    DATA_SYNTHETIC_DIR,
    MODELS_DIR,
    OUTPUTS_DIR,
    VOTES_FILENAME,
)
from mariodpo_v2.level_io import (
    iter_seed_levels,
    level_to_text,
    load_level,
    resolve_level_path,
)
from mariodpo_v2.pairs import (
    expand_by_weight,
    make_human_pairs,
    make_synthetic_pairs,
    score_levels,
)
from mariodpo_v2.utils import load_dotenv, set_seed, setup_logging
from mariodpo_v2.votes import iter_preference_pairs, load_votes

log = setup_logging()


def _load_judge():
    import joblib

    bundle = joblib.load(MODELS_DIR / "judge.pkl")
    return bundle["judge"]


def _ncd_refs(n: int, seed: int) -> list[str]:
    rng = random.Random(seed)
    originals = [load_level(p) for g, f, p in iter_seed_levels(["original"])]
    texts = [level_to_text(r) for r in originals]
    return rng.sample(texts, min(n, len(texts))) if texts else []


def _resolved_human_pairs(limit: int | None):
    bundle = load_votes(DATA_RAW_DIR / VOTES_FILENAME)
    out = []
    for p in iter_preference_pairs(bundle):
        wp = resolve_level_path(p.winner_level_id)
        lp = resolve_level_path(p.loser_level_id)
        if wp is None or lp is None:
            continue
        out.append((load_level(wp), load_level(lp), p.vote_id))
        if limit and len(out) >= limit:
            break
    return out


def _seed_pool(limit_per_gen: int | None, seed: int):
    rng = random.Random(seed)
    by_gen: dict[str, list] = {}
    for gen, fname, path in iter_seed_levels():
        by_gen.setdefault(gen, []).append(path)
    pool = []
    for gen, paths in by_gen.items():
        rng.shuffle(paths)
        chosen = paths[:limit_per_gen] if limit_per_gen else paths
        pool.extend(load_level(p) for p in chosen)
    return pool


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dummy", action="store_true")
    ap.add_argument("--win-cols", type=int, default=48)
    ap.add_argument("--human-weight", type=float, default=10.0)
    ap.add_argument("--margin", type=float, default=0.5)
    ap.add_argument("--n-synthetic", type=int, default=2000)
    ap.add_argument("--n-onpolicy", type=int, default=0)
    ap.add_argument("--sft-model", default="models/sft")
    ap.add_argument("--seed", type=int, default=42)
    args = ap.parse_args()

    load_dotenv()
    set_seed(args.seed)
    DATA_SYNTHETIC_DIR.mkdir(parents=True, exist_ok=True)
    OUTPUTS_DIR.mkdir(parents=True, exist_ok=True)

    judge = _load_judge()
    ncd_refs = _ncd_refs(8, args.seed)

    # --- Human pairs -------------------------------------------------------
    human_limit = 40 if args.dummy else None
    resolved = _resolved_human_pairs(human_limit)
    human_weight = 2.0 if args.dummy else args.human_weight
    human = make_human_pairs(resolved, win_cols=args.win_cols, weight=human_weight)
    log.info("Human pairs: %d (weight %.0f)", len(human), human_weight)

    # --- Synthetic: seed corpus -------------------------------------------
    seed_pool = _seed_pool(limit_per_gen=3 if args.dummy else None, seed=args.seed)
    scored = score_levels(judge, seed_pool, ncd_refs)
    log.info("Scored %d seed-corpus levels for synthetic pairing", len(scored))

    # --- Synthetic: on-policy (optional) ----------------------------------
    if args.n_onpolicy > 0 and not args.dummy:
        scored += _onpolicy_scored(args.sft_model, judge, ncd_refs,
                                   args.n_onpolicy, args.seed)
        log.info("Total scored levels incl. on-policy: %d", len(scored))

    n_syn = 50 if args.dummy else args.n_synthetic
    synthetic = make_synthetic_pairs(
        scored, n_pairs=n_syn, margin=args.margin,
        win_cols=args.win_cols, seed=args.seed,
    )
    log.info("Synthetic pairs (margin>%.2f): %d", args.margin, len(synthetic))

    # --- Expand (oversample) + write --------------------------------------
    all_records = human + synthetic
    expanded = expand_by_weight(all_records)
    random.Random(args.seed).shuffle(expanded)

    out_path = DATA_SYNTHETIC_DIR / "preference_pairs.jsonl"
    with out_path.open("w", encoding="utf-8") as fh:
        for rec in expanded:
            fh.write(json.dumps(rec) + "\n")

    stats = {
        "human_pairs": len(human),
        "synthetic_pairs": len(synthetic),
        "human_weight": human_weight,
        "expanded_total": len(expanded),
        "effective_human": sum(1 for r in expanded if r["source"] == "human"),
        "effective_synthetic": sum(1 for r in expanded if r["source"] == "synthetic"),
        "win_cols": args.win_cols,
        "margin": args.margin,
    }
    (DATA_SYNTHETIC_DIR / "pairs_stats.json").write_text(json.dumps(stats, indent=2))
    log.info("Wrote %d expanded records -> %s", len(expanded), out_path)
    log.info("Stats: %s", stats)

    _plot(scored, stats)


def _onpolicy_scored(sft_model, judge, ncd_refs, n, seed):
    from mariodpo_v2.generate import generate_level_columns
    from mariodpo_v2.modeling import has_cuda, load_model, load_tokenizer
    from mariodpo_v2.pairs import score_levels

    tok = load_tokenizer(sft_model)
    model = load_model(checkpoint=sft_model)
    if has_cuda():
        model = model.cuda()
    model.eval()
    levels = [
        generate_level_columns(model, tok, target_cols=180, seed=seed + i)
        for i in range(n)
    ]
    return score_levels(judge, levels, ncd_refs)


def _plot(scored, stats) -> None:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    fig, axes = plt.subplots(1, 2, figsize=(11, 4))
    axes[0].hist([s for _, s in scored], bins=30, color="steelblue")
    axes[0].set_title("Judge scores of synthetic-source levels")
    axes[0].set_xlabel("judge score"); axes[0].set_ylabel("count")

    axes[1].bar(["human\n(effective)", "synthetic"],
                [stats["effective_human"], stats["effective_synthetic"]],
                color=["darkorange", "steelblue"])
    axes[1].set_title("DPO dataset composition (after oversampling)")
    axes[1].set_ylabel("records")
    fig.tight_layout()
    fig.savefig(OUTPUTS_DIR / "preference_dataset.png", dpi=130)
    plt.close(fig)


if __name__ == "__main__":
    main()
